### ISSUE TITLE
Manifests to be applied to target cluster containing secrets should not be in configmaps on the management cluster

### ISSUE THREAD

**Issue by csrwng** [openshift/ibm-roks-toolkit#151]
See https://github.com/openshift/ibm-roks-toolkit/pull/150#pullrequestreview-594507353

The configmap should be changed to a secret. The bootstrap pod should look for both configmaps and secrets to apply.

**Comment by rtheis** [comment]
Fix https://github.com/openshift/ibm-roks-toolkit/pull/256.
