### ISSUE TITLE
Report cluster_version and cluster_infrastructure_provider metrics from within a ROKS cluster

### ISSUE THREAD

**Issue by csrwng** [openshift/ibm-roks-toolkit#23]
The kube-apiserver operator performs this function for a self-hosted cluster.
We need something to take its place in a ROKS cluster:
https://github.com/openshift/cluster-kube-apiserver-operator/blob/c7b1e077d913fbe6e89d4c10312346234e31e4e4/pkg/operator/configmetrics/configmetrics.go#L20

**Comment by derekwaynecarr** [comment]
the metric should be sourced from openshift-state-metrics in both self-hosted/external-hosted modes.

**Comment by csrwng** [comment]
Addressed by #58
/close
